# Generated by Django 4.0.5 on 2022-07-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inser', '0002_users_address_users_dob_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(),
        ),
    ]
